### ISSUE TITLE
Attribution OpenStreetMap manquante

### ISSUE THREAD

**Issue by Jean-BaptisteC** [betagouv/france-chaleur-urbaine#799]
Le site ne fait pas mention d'OpenStreetMap ni sur la carte ni dans les mentions légales.
Pouvez-vous ajouter une attribution sur votre carte en suivant les règles indiquées ici -> https://www.openstreetmap.org/copyright
Pouvez-vous assurer que l'attribution est aussi visible sur l'intégration de votre carte sur des sites tiers ?
Exemple:
- https://www.es-omega.net/omega-chauffage-urbain.htm

**Comment by totakoko** [comment]
Salut !
Merci pour ce retour. Les attributions ont en effet disparu dernièrement. C'était dû à un changement du côté de notre [fournisseur de tuiles](https://openmaptiles.geo.data.gouv.fr/). Ça a été patché donc les attributions sont revenues. :)

**Comment by Jean-BaptisteC** [comment]
Merci pour votre réactivité :)
