### ISSUE TITLE
Mettre les stats à jour dans "Qui sommes nous" ?

### ISSUE THREAD

**Issue by sylvinus** [betagouv/france-chaleur-urbaine#822]
Il y a une différence importante avec https://france-chaleur-urbaine.beta.gouv.fr/stats

https://github.com/betagouv/france-chaleur-urbaine/blob/a5d5dc331f619d92b3ef17357d9a5eb5efaf4ab6/src/data/home/data-number-fcu.json#L17

**Comment by totakoko** [comment]
Salut ! 
Merci pour le retour, on vient de [mettre à jour les chiffres](https://github.com/betagouv/france-chaleur-urbaine/pull/828) et harmoniser ceux de la page "qui sommes nous" (qu'on consulte un peu moins...).
