### ISSUE TITLE
Where did you define `NEXT_PUBLIC_SENTRY_DSN`?

### ISSUE THREAD

**Issue by alamenai** [betagouv/france-chaleur-urbaine#850]
Hi,

While I was checking the Sentry configuration to see how to access the dsn, I found that you access the dsn through `NEXT_PUBLIC_SENTRY_DSN` variable, however when I checked the env files, I did not find it.

I have this issue reported to Sentry and I would know if you have a solution for that:

https://github.com/getsentry/sentry-javascript/issues/13445

**Comment by totakoko** [comment]
Hi,
It's defined locally in a file named `.env.local` or in production via environment variables (we use Scalingo). Keep in mind that the container needs to be built with those variables.

**Comment by alamenai** [comment]
Exaclty @totakoko, I defined the variables in the pipeline environment variables, and we load them from there instead of putting them in the env.* files.
